In [1]:
import wandb
import pandas as pd

In [2]:
run_ids = ["8ih0c7g9", "1gr128qk"]

In [3]:
import wandb
def get_wandb_df(run_id):
    api = wandb.Api()
    run = api.run(f"cardiors/recordgraphs/{run_id}")
    df = run.history()
    df = df[["trainer/global_step", "_step", "epoch"] + [c for c in df.columns.to_list() if "valid" in c]]
    df = df[[c for c in df.columns.to_list() if not "hist" in c]]
    if run_id == "8ih0c7g9": label = "Covariates+SharedMLP"
    if run_id == "1gr128qk": label = "GNN+SharedMLP" 
    return df.assign(run_id=run_id, label=label)

In [4]:
dfs = pd.concat([get_wandb_df(run_id) for run_id in run_ids], axis=0).reset_index(drop=True)

In [5]:
dfs

,trainer/global_step,_step,epoch,valid/phecode_444-11 - Varicose veins of lower extremities_CIndex,valid/phecode_236-1 - Obesity_CIndex,valid/phecode_416-12 - Ventricular tachycardia_CIndex,valid/phecode_103 - Malignant neoplasm of the skin_CIndex,valid/phecode_437 - Vascular insufficiency of intestine_CIndex,valid/phecode_404 - Ischemic heart disease_CIndex,valid/mean_>1:1000,...,valid/phecode_007 - Hemophilus infection_CIndex,valid/phecode_542-1 - Fibrosis and cirrhosis of liver_CIndex,valid/phecode_052-3 - Varicella zoster virus_CIndex,valid/phecode_284-29 - Intentional self-harm*_CIndex,valid/phecode_528-2 - Vomiting_CIndex,valid/phecode_424 - Heart failure_CIndex,valid/phecode_684 - Diseases of hair and hair follicles_CIndex,valid/phecode_116-4 - Secondary malignant neoplasm of liver_CIndex,run_id,label
0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ih0c7g9,Covariates+SharedMLP
1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ih0c7g9,Covariates+SharedMLP
2,46.0,2,0.0,0.546705,0.514354,0.640022,0.608221,0.634821,0.659078,0.613117,...,0.592840,0.607157,0.569685,0.590105,0.573363,0.622771,0.614183,0.595570,8ih0c7g9,Covariates+SharedMLP
3,49.0,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ih0c7g9,Covariates+SharedMLP
4,49.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8ih0c7g9,Covariates+SharedMLP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,2349.0,146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1gr128qk,GNN+SharedMLP
456,2349.0,147,49.0,0.635980,0.646803,0.737496,0.628361,0.717957,0.697131,0.757362,...,0.804344,0.775547,0.799300,0.818692,0.664857,0.757863,0.827896,0.665196,1gr128qk,GNN+SharedMLP
457,2349.0,148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1gr128qk,GNN+SharedMLP
458,2396.0,149,50.0,0.644448,0.649040,0.731647,0.629394,0.714128,0.698439,0.757928,...,0.806185,0.776996,0.805647,0.825327,0.669476,0.761304,0.827118,0.665935,1gr128qk,GNN+SharedMLP
459,2399.0,150,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1gr128qk,GNN+SharedMLP

In [6]:
dfs.to_feather("test210214.feather")

,trainer/global_step,_step,_runtime,epoch,train/loss_step,_timestamp,valid/loss_step,gradients/graph_encoder.model.module_13.bias,gradients/graph_encoder.model.module_3.bias,gradients/graph_encoder.model.module_1.lin_r.bias,...,train/phecode_522 - Gastrointestinal inflammation_AUROC,train/phecode_410 - Inflammation of the heart [Carditis]_AUROC,train/phecode_511 - Gastro-esophageal reflux disease_AUROC,train/phecode_666 - Urticaria_AUROC,"train/phecode_281 - Substance abuse, dependence, and withdrawl_AUROC",train/phecode_527 - Abdominal pain_AUROC,train/phecode_112 - Malignant neoplasm of other and ill-defined sites_AUROC,train/phecode_673 - Skin changes due to chronic exposure to nonionizing radiation_AUROC,train/phecode_460 - Acute respiratory infection_AUROC,train/phecode_379 - Infection of the eye_AUROC
0,249,5,540,0.0,0.448360,1639822845,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14,22,682,NaN,NaN,1639822987,0.409161,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,47,55,701,NaN,NaN,1639823006,0.411881,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,50,58,703,NaN,NaN,1639823008,0.426107,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,449,81,782,1.0,0.398747,1639823087,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,7165,8393,42893,NaN,NaN,1639865198,0.151428,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,7196,8424,42911,NaN,NaN,1639865216,0.150779,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,7199,8427,42913,NaN,NaN,1639865218,0.148954,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,40599,8444,43117,106.0,0.146995,1639865422,NaN,"{'packedBins': {'min': -1503.67236328125, 'siz...","{'_type': 'histogram', 'packedBins': {'min': -...","{'_type': 'histogram', 'packedBins': {'min': -...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,40649,8445,43163,106.0,0.142904,1639865468,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
run_ids = {
    "Identity": 
    "Embedding":
    "GraphNN":
}

In [ ]:
for report in

In [10]:
import wandb
api = wandb.Api()
run = api.run("cardiors/recordgraphs/3u4d5sj9")

In [11]:
df = run.history()

In [12]:
df

,valid/auroc_hist,_step,_runtime,valid/mean_AUROC,_timestamp,trainer/global_step,epoch,train/loss_step,gradients/graph_encoder.model.module_13.bias,gradients/graph_encoder.model.module_3.bias,...,train/phecode_522 - Gastrointestinal inflammation_AUROC,train/phecode_102 - Malignant neoplasm of the thoracic and respiratory organs_AUROC,train/phecode_511 - Gastro-esophageal reflux disease_AUROC,train/phecode_808 - Syncope and collapse_AUROC,"train/phecode_281 - Substance abuse, dependence, and withdrawl_AUROC",train/phecode_527 - Abdominal pain_AUROC,train/phecode_801 - Cough_AUROC,train/phecode_112 - Malignant neoplasm of other and ill-defined sites_AUROC,train/phecode_673 - Skin changes due to chronic exposure to nonionizing radiation_AUROC,train/phecode_460 - Acute respiratory infection_AUROC
0,"{'values': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...",0,767,0.495696,1639749206,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1,824,NaN,1639749263,49.0,0.0,0.715763,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2,860,NaN,1639749299,99.0,0.0,0.578242,"{'packedBins': {'min': -6045.20703125, 'size':...","{'_type': 'histogram', 'packedBins': {'size': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3,896,NaN,1639749335,149.0,0.0,0.549331,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,4,932,NaN,1639749371,199.0,0.0,0.489913,"{'packedBins': {'count': 64, 'min': -4071.3525...","{'_type': 'histogram', 'packedBins': {'min': -...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,NaN,321,2117,NaN,1639750556,1649.0,4.0,0.251110,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,NaN,322,2151,NaN,1639750590,1699.0,4.0,0.250158,"{'_type': 'histogram', 'packedBins': {'count':...","{'_type': 'histogram', 'packedBins': {'size': ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,NaN,323,2186,NaN,1639750625,1749.0,4.0,0.245622,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,NaN,324,2221,NaN,1639750660,1799.0,4.0,0.242657,"{'_type': 'histogram', 'packedBins': {'min': -...","{'_type': 'histogram', 'packedBins': {'count':...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,NaN,325,2256,NaN,1639750695,1849.0,4.0,0.234569,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
import pandas as pd 
import wandb

api = wandb.Api()
entity, project = "cardiors", "recordgraphs"  # set to your entity and project 
runs = api.runs(entity + "/" + project) 

summary_list, config_list, name_list = [], [], []
for run in runs: 
    # .summary contains the output keys/values for metrics like accuracy.
    #  We call ._json_dict to omit large files 
    summary_list.append(run.summary._json_dict)

    # .config contains the hyperparameters.
    #  We remove special values that start with _.
    config_list.append(
        {k: v for k,v in run.config.items()
         if not k.startswith('_')})

    # .name is the human-readable name of the run.
    name_list.append(run.name)

runs_df = pd.DataFrame({
    "summary": summary_list,
    "config": config_list,
    "name": name_list
    })

In [16]:
runs_df

,summary,config,name
0,{},{},glowing-vortex-119
1,{'train/phecode_487 - Hemorrhage from respirat...,"{'head': None, 'loss': 'FocalBCEWithLogitsLoss...",dauntless-galaxy-118
2,{'_wandb': {'runtime': 632}},"{'head': None, 'loss': 'FocalBCEWithLogitsLoss...",stellar-shape-117
3,{'_wandb': {'runtime': 639}},{},smart-deluge-116
4,{'_wandb': {'runtime': 669}},{},quiet-plasma-115
...,...,...,...
69,{'_wandb': {'runtime': 465}},{},fearless-feather-5
70,{'_wandb': {'runtime': 67}},{},rare-frost-4
71,{'_wandb': {'runtime': 26}},{},fresh-disco-3
72,{'_wandb': {'runtime': 8}},{},stoic-wood-2
73,{'_wandb': {'runtime': 9}},{},driven-dust-1

In [14]:
phecodes = [c for c in df.columns.to_list() if "phecode_" in c]

['valid/phecode_138 - Benign neoplasm of the skin_AUROC',
 'valid/phecode_678 - Other skin and connective tissue disorders_AUROC',
 'valid/phecode_290 - Reaction to severe stress, and adjustment disorders_AUROC',
 'valid/phecode_200 - Disorders of thyroid gland_AUROC',
 'valid/phecode_662 - Rosacea_AUROC',
 'valid/phecode_070 - Candidiasis_AUROC',
 'valid/phecode_419 - Presence of cardiac device_AUROC',
 'valid/phecode_121 - Leukemia_AUROC',
 'valid/phecode_627 - Menopausal and postmenopausal disorders_AUROC',
 'valid/phecode_592 - Cystitis and urethritis_AUROC',
 'valid/phecode_983 - Family history of other endocrine and metabolic diseases_AUROC',
 'valid/phecode_144 - Gynecological benign neoplasms_AUROC',
 'valid/phecode_103 - Malignant neoplasm of the skin_AUROC',
 'valid/phecode_333 - Sleep disorders_AUROC',
 'valid/phecode_469 - Bronchitis_AUROC',
 'valid/phecode_594 - Abnormality of urination_AUROC',
 'valid/phecode_351 - Disturbances of skin sensation_AUROC',
 'valid/phecode_120 - Hemo onc - by cell of origin_AUROC',
 'valid/phecode_600 - Benign prostatic hyperplasia_AUROC',
 'valid/phecode_610 - Benign mammary dysplasias_AUROC',
 'valid/phecode_112 - Malignant neoplasm of other and ill-defined sites_AUROC',
 'valid/phecode_585 - Kidney stone disease_AUROC',
 'valid/phecode_374 - Disorders of the retina_AUROC',
 'valid/phecode_446 - Hypotension_AUROC',
 'valid/phecode_812 - Edema_AUROC',
 'valid/phecode_202 - Diabetes mellitus_AUROC',
 'valid/phecode_829 - Nonspecific findings on examination of blood_AUROC',
 'valid/phecode_557 - Gastrointestinal hemorrhage_AUROC',
 'valid/phecode_523 - Diverticular disease [Bowel diverticulosis]_AUROC',
 'valid/phecode_236 - Overweight and obesity_AUROC',
 'valid/phecode_088 - Sexually transmitted disease_AUROC',
 'valid/phecode_715 - Non-inflammatory spondylopathy_AUROC',
 'valid/phecode_510 - Diseases of esophagus_AUROC',
 'valid/phecode_101 - Malignant neoplasm of the digestive organs_AUROC',
 'valid/phecode_136 - Benign neoplasm of the digestive organs_AUROC',
 'valid/phecode_705 - Rheumatoid arthritis and other inflammatory polyarthropathies_AUROC',
 'valid/phecode_483 - Pleural effusion_AUROC',
 'valid/phecode_330 - Epilepsy, recurrent seizures, convulsions_AUROC',
 'valid/phecode_336 - Mononeuropathies_AUROC',
 'valid/phecode_092 - Bacteremia, Sepsis, and SIRS_AUROC',
 'valid/phecode_288 - Anxiety disorders_AUROC',
 'valid/phecode_294 - Sexual dysfunction and disorders_AUROC',
 'valid/phecode_308 - Signs and symptoms involving emotional state_AUROC',
 'valid/phecode_908 - Edema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium_AUROC',
 'valid/phecode_468 - Pneumonia_AUROC',
 'valid/phecode_413 - Heart valve disorders_AUROC',
 'valid/phecode_673 - Skin changes due to chronic exposure to nonionizing radiation_AUROC',
 'valid/phecode_513 - Peptic ulcer_AUROC',
 'valid/phecode_591 - Urinary tract infection_AUROC',
 'valid/phecode_528 - Nausea and vomiting_AUROC',
 'valid/phecode_668 - Dermatitis [eczema]_AUROC',
 'valid/phecode_807 - Malaise and fatigue_AUROC',
 'valid/phecode_440 - Embolism and thrombosis_AUROC',
 'valid/phecode_875 - Newborn affected by maternal conditions_AUROC',
 'valid/phecode_726 - Osteoporosis and low bone density_AUROC',
 'valid/phecode_116 - Secondary malignant neoplasm_AUROC',
 'valid/phecode_525 - Intestinal malabsorption_AUROC',
 'valid/phecode_524 - Functional intestinal disorder_AUROC',
 'valid/phecode_488 - Abnormalities of breathing_AUROC',
 'valid/phecode_416 - Cardiac arrhythmia and conduction disorders_AUROC',
 'valid/phecode_050 - Enterovirus_AUROC',
 'valid/phecode_471 - Other disorders of nose and nasal sinuses_AUROC',
 'valid/phecode_801 - Cough_AUROC',
 'valid/phecode_239 - Hyperlipidemia_AUROC',
 'valid/phecode_800 - Chest pain_AUROC',
 'valid/phecode_439 - Hemorrhoids_AUROC',
 'valid/phecode_718 - Back pain_AUROC',
 'valid/phecode_230 - Malnutrition and underweight_AUROC',
 'valid/phecode_626 - Disorders of menstruation and other abnormal bleeding from female genital tract_AUROC',
 'valid/phecode_181 - Autoimmune disease_AUROC',
 'valid/phecode_716 - Intervertebral disc disorder_AUROC',
 'valid/phecode_433 - Other cerebrovascular disease_AUROC',
 'valid/phecode_396 - Hearing impairment_AUROC',
 'valid/phecode_486 - Other respiratory disorders_AUROC',
 'valid/phecode_507 - Lesions of mouth_AUROC',
 'valid/phecode_367 - Inflammation of the eye_AUROC',
 'valid/phecode_360 - Inflammation of eyelids_AUROC',
 'valid/phecode_550 - Disorders of the gallbladder_AUROC',
 'valid/phecode_472 - Diseases of vocal cords and larynx, not elsewhere classified_AUROC',
 'valid/phecode_444 - Venous insufficiency_AUROC',
 'valid/phecode_808 - Syncope and collapse_AUROC',
 'valid/phecode_462 - Sinusitis_AUROC',
 'valid/phecode_335 - Nerve root and plexus disorders_AUROC',
 'valid/phecode_107 - Malignant neoplasm of male genitalia_AUROC',
 'valid/phecode_124 - Myeloproliferative disorder_AUROC',
 'valid/phecode_010 - Corynebacterium_AUROC',
 'valid/phecode_006 - Neisseria_AUROC',
 'valid/phecode_164 - Anemia_AUROC',
 'valid/phecode_089 - Infections_AUROC',
 'valid/phecode_371 - Cataract_AUROC',
 'valid/phecode_122 - Lymphoma_AUROC',
 'valid/phecode_331 - Headache_AUROC',
 'valid/phecode_328 - Dementias and cerebral degeneration_AUROC',
 'valid/phecode_522 - Gastrointestinal inflammation_AUROC',
 'valid/phecode_280 - Substance related disorders_AUROC',
 'valid/phecode_702 - Infective and reactive arthropathies_AUROC',
 'valid/phecode_401 - Hypertension_AUROC',
 'valid/phecode_511 - Gastro-esophageal reflux disease_AUROC',
 'valid/phecode_709 - Acquired deformities of fingers and toes_AUROC',
 'valid/phecode_375 - Abnormal intraocular pressure_AUROC',
 'valid/phecode_095 - Sequela of infection_AUROC',
 'valid/phecode_596 - Other disorders of bladder_AUROC',
 'valid/phecode_282 - Nicotine dependence (current and history of)_AUROC',
 'valid/phecode_052 - Herpesvirus_AUROC',
 'valid/phecode_362 - Other disorders of the eyelids_AUROC',
 'valid/phecode_840 - Allergy_AUROC',
 'valid/phecode_395 - Other diseases of inner ear_AUROC',
 'valid/phecode_721 - Synoviopathy and bursopathy_AUROC',
 'valid/phecode_950 - Puerperal infection or fever_AUROC',
 'valid/phecode_350 - Other symptoms involving nervous system_AUROC',
 'valid/phecode_354 - Dizziness and giddiness_AUROC',
 'valid/phecode_682 - Other follicular disorders_AUROC',
 'valid/phecode_108 - Malignant neoplasm of the urinary tract_AUROC',
 'valid/phecode_686 - Chronic ulcer of skin_AUROC',
 'valid/phecode_479 - Pulmonary insufficiency and acute respiratory distress syndrome_AUROC',
 'valid/phecode_476 - Bronchiectasis_AUROC',
 'valid/phecode_863 - Transitory neonatal endocrine disorders_AUROC',
 'valid/phecode_670 - Seborrheic keratosis_AUROC',
 'valid/phecode_424 - Heart failure_AUROC',
 'valid/phecode_665 - Psoriasis_AUROC',
 'valid/phecode_247 - Disorders of mineral metabolism and mineral deficiencies_AUROC',
 'valid/phecode_679 - Skin symptoms_AUROC',
 'valid/phecode_363 - Disorders of lacrimal system_AUROC',
 'valid/phecode_105 - Malignant neoplasm of the breast_AUROC',
 'valid/phecode_581 - Renal tubulo-interstitial diseases_AUROC',
 'valid/phecode_583 - Chronic kidney disease_AUROC',
 'valid/phecode_586 - Other disorders of the kidney and ureters_AUROC',
 'valid/phecode_436 - Atherosclerosis [ASCVD]_AUROC',
 'valid/phecode_809 - Pain_AUROC',
 'valid/phecode_593 - Hematuria_AUROC',
 'valid/phecode_291 - Dissociative, conversion and factitious disorders_AUROC',
 'valid/phecode_460 - Acute respiratory infection_AUROC',
 'valid/phecode_448 - Peripheral vascular disease_AUROC',
 'valid/phecode_527 - Abdominal pain_AUROC',
 'valid/phecode_477 - Inhalation lung injury_AUROC',
 'valid/phecode_723 - Enthesopathy-Enthesitis-Tendinopathy_AUROC',
 'valid/phecode_856 - Infections in newborn_AUROC',
 'valid/phecode_324 - Extrapyramidal and movement disorders_AUROC',
 'valid/phecode_132 - Sequelae of cancer_AUROC',
 'valid/phecode_608 - Other disorders of male genital organs_AUROC',
 'valid/phecode_614 - Inflammatory diseases of female pelvic organs_AUROC',
 'valid/phecode_481 - Interstitial pulmonary diseases_AUROC',
 'valid/phecode_865 - Neonatal disorders of digestive system_AUROC',
 'valid/phecode_660 - Infection of the skin_AUROC',
 'valid/phecode_391 - Disorders of the middle ear_AUROC',
 'valid/phecode_431 - Stroke and transient cerebral ischemic attacks_AUROC',
 'valid/phecode_819 - General symptoms and other findings_AUROC',
 'valid/phecode_466 - Tonsillitis and adenoiditis_AUROC',
 'valid/phecode_130 - Cancer (solid tumor, excluding BCC)_AUROC',
 'valid/phecode_084 - Parasites_AUROC',
 'valid/phecode_582 - Acute kidney failure_AUROC',
 'valid/phecode_619 - Noninflammatory female genital disorders_AUROC',
 'valid/phecode_061 - Influenza virus_AUROC',
 'valid/phecode_292 - Somatoform disorders_AUROC',
 'valid/phecode_475 - Asthma_AUROC',
 'valid/phecode_988 - Family history of cardiovascular disease_AUROC',
 'valid/phecode_520 - Hernia_AUROC',
 'valid/phecode_056 - Human papillomavirus_AUROC',
 'valid/phecode_123 - Multiple myeloma and malignant plasma cell neoplasms_AUROC',
 'valid/phecode_232 - Vitamin deficiencies_AUROC',
 'valid/phecode_463 - Rhinitis and nasal congestion_AUROC',
 'valid/phecode_625 - Pain and other symptoms associated with female genital organs_AUROC',
 'valid/phecode_700 - Diffuse diseases of connective tissue_AUROC',
 'valid/phecode_722 - Fasciopathy_AUROC',
 'valid/phecode_703 - Chrystal arthropathies_AUROC',
 'valid/phecode_487 - Hemorrhage from respiratory passages_AUROC',
 'valid/phecode_708 - Osteoarthritis_AUROC',
 'valid/phecode_713 - Symptoms related to joints_AUROC',
 'valid/phecode_526 - Intestinal infection_AUROC',
 'valid/phecode_618 - Genital prolapse_AUROC',
 'valid/phecode_979 - Transplated organ_AUROC',
 'valid/phecode_530 - Disease of anus and rectum_AUROC',
 'valid/phecode_727 - Other disorders of bone_AUROC',
 'valid/phecode_542 - Chronic liver disease and sequelae_AUROC',
 'valid/phecode_403 - Angina pectoris_AUROC',
 'valid/phecode_841 - Drug and medical agent allergy_AUROC',
 'valid/phecode_286 - Mood [affective] disorders_AUROC',
 'valid/phecode_004 - Streptococcus_AUROC',
 'valid/phecode_256 - Disorders of fluid, electrolyte and acid-base balance_AUROC',
 'valid/phecode_474 - Chronic obstructive pulmonary disease [COPD]_AUROC',
 'valid/phecode_465 - Pharyngitis_AUROC',
 'valid/phecode_404 - Ischemic heart disease_AUROC',
 'valid/phecode_613 - Other nonmalignant breast conditions_AUROC',
 'valid/phecode_106 - Gynecological malignant neoplasms_AUROC',
 'valid/phecode_529 - Symptoms involving digestive system_AUROC',
 'valid/phecode_909 - Diabetes mellitus or abnormal glucose in pregnancy, childbirth, and the puerperium_AUROC',
 'valid/phecode_724 - Other symptoms and disorders of the soft tissue_AUROC',
 'valid/phecode_005 - Mycobacteria_AUROC',
 'valid/phecode_139 - Benign sarcoma-related cancers_AUROC',
 'valid/phecode_711 - Disorder of patella_AUROC',
 'valid/phecode_390 - Disorders of external ear_AUROC',
 'valid/phecode_981 - Family history of malignant neoplasm_AUROC',
 'valid/phecode_102 - Malignant neoplasm of the thoracic and respiratory organs_AUROC',
 'valid/phecode_402 - Elevated blood pressure reading without diagnosis of hypertension_AUROC',
 'valid/phecode_400 - Rheumatic fever and chronic rheumatic heart diseases_AUROC',
 'valid/phecode_281 - Substance abuse, dependence, and withdrawl_AUROC',
 'valid/phecode_916 - Infections and carrier state in pregnancy_AUROC',
 'valid/phecode_926 - Mental disorders complicating pregnancy, childbirth and the puerperium_AUROC',
 'valid/phecode_417 - Abnormalities of heart beat_AUROC',
 'valid/phecode_160 - Nutritional anemias_AUROC',
 'train/phecode_101 - Malignant neoplasm of the digestive organs_AUROC',
 'train/phecode_660 - Infection of the skin_AUROC',
 'train/phecode_619 - Noninflammatory female genital disorders_AUROC',
 'train/phecode_239 - Hyperlipidemia_AUROC',
 'train/phecode_256 - Disorders of fluid, electrolyte and acid-base balance_AUROC',
 'train/phecode_809 - Pain_AUROC',
 'train/phecode_471 - Other disorders of nose and nasal sinuses_AUROC',
 'train/phecode_613 - Other nonmalignant breast conditions_AUROC',
 'train/phecode_416 - Cardiac arrhythmia and conduction disorders_AUROC',
 'train/phecode_360 - Inflammation of eyelids_AUROC',
 'train/phecode_596 - Other disorders of bladder_AUROC',
 'train/phecode_865 - Neonatal disorders of digestive system_AUROC',
 'train/phecode_475 - Asthma_AUROC',
 'train/phecode_477 - Inhalation lung injury_AUROC',
 'train/phecode_395 - Other diseases of inner ear_AUROC',
 'train/phecode_523 - Diverticular disease [Bowel diverticulosis]_AUROC',
 'train/phecode_600 - Benign prostatic hyperplasia_AUROC',
 'train/phecode_160 - Nutritional anemias_AUROC',
 'train/phecode_586 - Other disorders of the kidney and ureters_AUROC',
 'train/phecode_056 - Human papillomavirus_AUROC',
 'train/phecode_678 - Other skin and connective tissue disorders_AUROC',
 'train/phecode_247 - Disorders of mineral metabolism and mineral deficiencies_AUROC',
 'train/phecode_483 - Pleural effusion_AUROC',
 'train/phecode_614 - Inflammatory diseases of female pelvic organs_AUROC',
 'train/phecode_181 - Autoimmune disease_AUROC',
 'train/phecode_716 - Intervertebral disc disorder_AUROC',
 'train/phecode_476 - Bronchiectasis_AUROC',
 'train/phecode_404 - Ischemic heart disease_AUROC',
 'train/phecode_983 - Family history of other endocrine and metabolic diseases_AUROC',
 'train/phecode_288 - Anxiety disorders_AUROC',
 'train/phecode_202 - Diabetes mellitus_AUROC',
 'train/phecode_679 - Skin symptoms_AUROC',
 'train/phecode_520 - Hernia_AUROC',
 'train/phecode_391 - Disorders of the middle ear_AUROC',
 'train/phecode_396 - Hearing impairment_AUROC',
 'train/phecode_625 - Pain and other symptoms associated with female genital organs_AUROC',
 'train/phecode_829 - Nonspecific findings on examination of blood_AUROC',
 'train/phecode_481 - Interstitial pulmonary diseases_AUROC',
 'train/phecode_486 - Other respiratory disorders_AUROC',
 'train/phecode_138 - Benign neoplasm of the skin_AUROC',
 'train/phecode_840 - Allergy_AUROC',
 'train/phecode_981 - Family history of malignant neoplasm_AUROC',
 'train/phecode_507 - Lesions of mouth_AUROC',
 'train/phecode_292 - Somatoform disorders_AUROC',
 'train/phecode_335 - Nerve root and plexus disorders_AUROC',
 'train/phecode_557 - Gastrointestinal hemorrhage_AUROC',
 'train/phecode_462 - Sinusitis_AUROC',
 'train/phecode_863 - Transitory neonatal endocrine disorders_AUROC',
 'train/phecode_950 - Puerperal infection or fever_AUROC',
 'train/phecode_626 - Disorders of menstruation and other abnormal bleeding from female genital tract_AUROC',
 'train/phecode_856 - Infections in newborn_AUROC',
 'train/phecode_116 - Secondary malignant neoplasm_AUROC',
 'train/phecode_419 - Presence of cardiac device_AUROC',
 'train/phecode_875 - Newborn affected by maternal conditions_AUROC',
 'train/phecode_088 - Sexually transmitted disease_AUROC',
 'train/phecode_122 - Lymphoma_AUROC',
 'train/phecode_529 - Symptoms involving digestive system_AUROC',
 'train/phecode_436 - Atherosclerosis [ASCVD]_AUROC',
 'train/phecode_336 - Mononeuropathies_AUROC',
 'train/phecode_721 - Synoviopathy and bursopathy_AUROC',
 'train/phecode_144 - Gynecological benign neoplasms_AUROC',
 'train/phecode_581 - Renal tubulo-interstitial diseases_AUROC',
 'train/phecode_713 - Symptoms related to joints_AUROC',
 'train/phecode_092 - Bacteremia, Sepsis, and SIRS_AUROC',
 'train/phecode_105 - Malignant neoplasm of the breast_AUROC',
 'train/phecode_668 - Dermatitis [eczema]_AUROC',
 'train/phecode_722 - Fasciopathy_AUROC',
 'train/phecode_291 - Dissociative, conversion and factitious disorders_AUROC',
 'train/phecode_542 - Chronic liver disease and sequelae_AUROC',
 'train/phecode_530 - Disease of anus and rectum_AUROC',
 'train/phecode_330 - Epilepsy, recurrent seizures, convulsions_AUROC',
 'train/phecode_582 - Acute kidney failure_AUROC',
 'train/phecode_294 - Sexual dysfunction and disorders_AUROC',
 'train/phecode_440 - Embolism and thrombosis_AUROC',
 'train/phecode_591 - Urinary tract infection_AUROC',
 'train/phecode_487 - Hemorrhage from respiratory passages_AUROC',
 'train/phecode_439 - Hemorrhoids_AUROC',
 'train/phecode_800 - Chest pain_AUROC',
 'train/phecode_004 - Streptococcus_AUROC',
 'train/phecode_525 - Intestinal malabsorption_AUROC',
 'train/phecode_926 - Mental disorders complicating pregnancy, childbirth and the puerperium_AUROC',
 'train/phecode_308 - Signs and symptoms involving emotional state_AUROC',
 'train/phecode_488 - Abnormalities of breathing_AUROC',
 'train/phecode_819 - General symptoms and other findings_AUROC',
 'train/phecode_433 - Other cerebrovascular disease_AUROC',
 'train/phecode_050 - Enterovirus_AUROC',
 'train/phecode_463 - Rhinitis and nasal congestion_AUROC',
 'train/phecode_089 - Infections_AUROC',
 'train/phecode_662 - Rosacea_AUROC',
 'train/phecode_232 - Vitamin deficiencies_AUROC',
 'train/phecode_061 - Influenza virus_AUROC',
 'train/phecode_103 - Malignant neoplasm of the skin_AUROC',
 'train/phecode_618 - Genital prolapse_AUROC',
 'train/phecode_290 - Reaction to severe stress, and adjustment disorders_AUROC',
 'train/phecode_711 - Disorder of patella_AUROC',
 'train/phecode_608 - Other disorders of male genital organs_AUROC',
 'train/phecode_700 - Diffuse diseases of connective tissue_AUROC',
 'train/phecode_084 - Parasites_AUROC',
 'train/phecode_124 - Myeloproliferative disorder_AUROC',
 'train/phecode_593 - Hematuria_AUROC',
 'train/phecode_610 - Benign mammary dysplasias_AUROC',
 'train/phecode_708 - Osteoarthritis_AUROC',
 'train/phecode_431 - Stroke and transient cerebral ischemic attacks_AUROC',
 'train/phecode_526 - Intestinal infection_AUROC',
 'train/phecode_354 - Dizziness and giddiness_AUROC',
 'train/phecode_401 - Hypertension_AUROC',
 'train/phecode_465 - Pharyngitis_AUROC',
 'train/phecode_585 - Kidney stone disease_AUROC',
 'train/phecode_400 - Rheumatic fever and chronic rheumatic heart diseases_AUROC',
 'train/phecode_550 - Disorders of the gallbladder_AUROC',
 'train/phecode_351 - Disturbances of skin sensation_AUROC',
 'train/phecode_468 - Pneumonia_AUROC',
 'train/phecode_472 - Diseases of vocal cords and larynx, not elsewhere classified_AUROC',
 'train/phecode_841 - Drug and medical agent allergy_AUROC',
 'train/phecode_510 - Diseases of esophagus_AUROC',
 'train/phecode_583 - Chronic kidney disease_AUROC',
 'train/phecode_417 - Abnormalities of heart beat_AUROC',
 'train/phecode_402 - Elevated blood pressure reading without diagnosis of hypertension_AUROC',
 'train/phecode_120 - Hemo onc - by cell of origin_AUROC',
 'train/phecode_979 - Transplated organ_AUROC',
 'train/phecode_446 - Hypotension_AUROC',
 'train/phecode_121 - Leukemia_AUROC',
 'train/phecode_136 - Benign neoplasm of the digestive organs_AUROC',
 'train/phecode_350 - Other symptoms involving nervous system_AUROC',
 'train/phecode_333 - Sleep disorders_AUROC',
 'train/phecode_705 - Rheumatoid arthritis and other inflammatory polyarthropathies_AUROC',
 'train/phecode_718 - Back pain_AUROC',
 'train/phecode_367 - Inflammation of the eye_AUROC',
 'train/phecode_108 - Malignant neoplasm of the urinary tract_AUROC',
 'train/phecode_444 - Venous insufficiency_AUROC',
 'train/phecode_164 - Anemia_AUROC',
 'train/phecode_107 - Malignant neoplasm of male genitalia_AUROC',
 'train/phecode_807 - Malaise and fatigue_AUROC',
 'train/phecode_052 - Herpesvirus_AUROC',
 'train/phecode_375 - Abnormal intraocular pressure_AUROC',
 'train/phecode_715 - Non-inflammatory spondylopathy_AUROC',
 'train/phecode_286 - Mood [affective] disorders_AUROC',
 'train/phecode_466 - Tonsillitis and adenoiditis_AUROC',
 'train/phecode_726 - Osteoporosis and low bone density_AUROC',
 'train/phecode_812 - Edema_AUROC',
 'train/phecode_006 - Neisseria_AUROC',

In [13]:
df[]

,valid/phecode_138 - Benign neoplasm of the skin_AUROC,valid/phecode_678 - Other skin and connective tissue disorders_AUROC,"valid/phecode_290 - Reaction to severe stress, and adjustment disorders_AUROC",valid/phecode_200 - Disorders of thyroid gland_AUROC,valid/phecode_662 - Rosacea_AUROC,valid/phecode_070 - Candidiasis_AUROC,valid/phecode_419 - Presence of cardiac device_AUROC,valid/phecode_121 - Leukemia_AUROC,valid/phecode_627 - Menopausal and postmenopausal disorders_AUROC,valid/phecode_592 - Cystitis and urethritis_AUROC,...,train/phecode_522 - Gastrointestinal inflammation_AUROC,train/phecode_102 - Malignant neoplasm of the thoracic and respiratory organs_AUROC,train/phecode_511 - Gastro-esophageal reflux disease_AUROC,train/phecode_808 - Syncope and collapse_AUROC,"train/phecode_281 - Substance abuse, dependence, and withdrawl_AUROC",train/phecode_527 - Abdominal pain_AUROC,train/phecode_801 - Cough_AUROC,train/phecode_112 - Malignant neoplasm of other and ill-defined sites_AUROC,train/phecode_673 - Skin changes due to chronic exposure to nonionizing radiation_AUROC,train/phecode_460 - Acute respiratory infection_AUROC
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
run.history()

,trainer/global_step,_step,_runtime,epoch,train/loss_step,_timestamp,valid/loss_step,valid/phecode_596_AUROC,valid/phecode_462_AUROC,valid/phecode_136_AUROC,...,gradients/graph_encoder.model.module_7.lin_l.bias,gradients/graph_encoder.model.module_7.att,gradients/graph_encoder.model.module_12.mean_scale,gradients/graph_encoder.model.module_1.lin_l.weight,gradients/graph_encoder.model.module_13.self_loop_fill,gradients/graph_encoder.model.module_1.lin_edge.weight,gradients/head.bias,gradients/graph_encoder.model.module_1.lin_l.bias,valid/auroc_hist,valid/mean_AUROC
0,349,7,1091,0.0,0.44803,1639660587,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33,41,1151,NaN,NaN,1639660647,0.442381,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,57,65,1165,NaN,NaN,1639660661,0.453623,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,380,77,1172,0.0,NaN,1639660668,NaN,0.327601,0.353575,0.443104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,85,105,1473,NaN,NaN,1639660969,0.367628,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,13212,15474,65960,NaN,NaN,1639725456,0.184727,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,13240,15502,65973,NaN,NaN,1639725469,0.182229,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,13285,15559,66290,NaN,NaN,1639725786,0.185692,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,13293,15567,66295,NaN,NaN,1639725791,0.192796,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,13314,15588,66307,NaN,NaN,1639725803,0.181778,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN